version: '3.9'

services:
  accounts_db:
    image: 'bitnami/postgresql:13'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_DATABASE=accounts_database
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: '1.0'
