name: Accounts Server CI Workflow

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/server/accounts/**"

jobs:
  test-routine:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      PACKAGE_NAME: packages/server/accounts

    steps:
      - uses: actions/checkout@v2
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Sao_Paulo
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          NODE_ENV: test
      - run: npm i -g npm
      - run: npm i
      - run: npm run test:coverage --workspace=$PACKAGE_NAME
