name: Accounts Server CI Workflow

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "packages/server/accounts/**"

jobs:
  test-routine:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Sao_Paulo
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          NODE_ENV: test
      - run: npm i -g npm
      - run: npm i
      - run: npm run test:coverage --workspace=packages/server/accounts

  deployment-step:
    runs-on: ubuntu-latest
    needs: test-routine

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "batata-1632181839939"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: "main"
          appdir: packages/server/accounts
